version = 0.1
[default.deploy.parameters]
stack_name = "fastapi-lambda"
resolve_s3 = true
s3_prefix = "fastapi-lambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repository = "FastApiFunction=account-id.dkr.ecr.us-east-1.amazonaws.com/fastapi-lambda"
